### ISSUE TITLE
Rationale for each container

### ISSUE THREAD

**Issue by maggie44** [klutchell/balena-bookstack#3]
Useful repo, thanks. 

Could you elaborate on the rationale/workflow? Why incorporate Redis? And what is the thinking behind Duplicati as a default install, if it does intermittent sql dumps occasionally anyway? Restoration? 

Which of these components is the reason it is limited to 64 bit RPIs? If just MariaDB, could consider limuxserver image which supposedly supports ARM: https://docs.linuxserver.io/images/docker-mariadb

**Comment by klutchell** [comment]
Hey @maggie0002! Those are very good questions. I'll attempt to explain myself and update the README accordingly!

Redis an in-memory key-value database that can be used to improve the performance of applications via memory caching, where frequently-requested objects are stored in memory for faster retrieval. I'm not a expert beyond setting it up, but some form of memory caching is recommended for a small performance bump in applications like Bookstack and Nextcloud. It is completely optional though, so feel free to remove it from your setup.

I use Duplicati on most of my devices as a way to ensure I have offsite backups of the data in case of SD card corruption or other data loss. It also makes it convenient to migrate the data to a new device and memory card if needed. I don't trust a backup of a database that is currently in use, so sqldump ensures there is no corruption due to open database files. On restoration if the database doesn't immediately work, I can import the sqldump file.

That being said, I'm considering moving sqldump & duplicati to an optional branch on this repo to keep the main branch cleaner. Don't be surprised if in a future update you no longer see those services on the main branch.

This repo is not limited to 64-bit devices any more. I'll update the documentation accordingly.

I hope I answered your questions!

**Comment by maggie44** [comment]
Thanks for the info. 

Redis makes sense, I guess there is a case to be made for reducing SD card writes too which is always an advantage and in line with Balena's approach.

Sqldump looks pretty light as it reuses the container, and may have some advantages on devices that have a tendency to have their power pulled suddenly. Problem being, to offer a Sqldump probably calls for a way to then restore from the Sqldump that is compatible with a fleet of devices. Not sure how that can be done. 

I think you're right about offering them as separate repos, especially Duplicati as it is additional weight without choice. Especially for pulling from the Balena Hub where I assume the idea is for one-click installs, rather than modifying Docker files. Duplicati however may make a nice additional Balena Hub contribution as a standalone install. 

I had some other questions answered for me over on the BookStack repo that may be useful for Balena users, so sharing here so it's searchable:

- Offline use requires a few adaptions of the BookStack components that depend on online use:

https://github.com/BookStackApp/BookStack/issues/2409

- BookStack has the ability to set custom logos and names, but at the moment you cannot do it at build time. Obviously this is a bit of an issue for users trying to deploy a fleet of devices:

https://github.com/BookStackApp/BookStack/issues/652#issuecomment-743945521

**Comment by klutchell** [comment]
Great, thanks for the extra links!

Unfortunately importing an sqldump is still a manual process, as you said. I didn't make it a priority to streamline since I'm hoping it rarely has to be done, but at least the data is there if we need it.
